{{ range $key, $val := .Values.apps }} #для того что бы перебрать лист или карту, почти как foreach
  {{- template "decoder.deployment" $val}}# Генерация деплоймента, передать в качестве контекста мапу, возможно передать 2 параметра
---
  {{- template "decoder.service" $val}}# Генерация деплоймента, передать в качестве контекста мапу
--- # т.к. работаем в цикле нужно добавлять и после
{{ end}}