
variables:
  JAVA_VERSION: 17
  APP_IMAGE: test-app
  APP_TAG: ${CI_COMMIT_TAG}

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - build_image

cache:
  key: "${CI_COMMIT_REF_SLUG}-build-cache"
  paths:
    - /build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: openjdk:${JAVA_VERSION}-jdk-alpine3.14
  script:
    - ./gradlew bootJar

test-job:
  stage: test
  image: openjdk:${JAVA_VERSION}-jdk-alpine3.14
  script:
    - ./gradlew test
