spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}.${POSTGRES_NAMESPACE}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
