---
# Source: blog/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
# Source: blog/templates/app.yml
apiVersion: v1
data:
  POSTGRES_DB: YmxvZw==
  POSTGRES_DRIVER: b3JnLnBvc3RncmVzcWwuRHJpdmVy
  POSTGRES_PASSWORD: bWFpbl9wYXNz
  POSTGRES_PORT: NTQzMg==
  POSTGRES_URL: MTkyLjE2OC4xLjgx
  POSTGRES_USER: bWFpbl91c2Vy
kind: Secret
metadata:
  name: db-env-secret
  namespace: gitlab
  labels:
    app.kubernetes.io/name: blog-db-env-secret
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: blog/templates/liquidbase-configfile.yml
apiVersion: v1
kind: ConfigMap #хранит параметры контейнера
metadata:
  name: liquidbase-configfile #имя конфига
  namespace: gitlab
data: #Данные хранящие в мапе
  liquibase.properties: |
    url= jdbc:postgresql://192.168.1.81:5432/blog
    username= main_user
    password= main_pass
    changeLogFile= changelog/db.changelog-master.yml
    driver= org.postgresql.Driver
---
# Source: blog/templates/app.yml
apiVersion: v1
kind: Service
metadata:
  name: blog-app-svc
  namespace: gitlab
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: blog-app
    app.kubernetes.io/instance: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30022
---
# Source: blog/templates/app.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deployment
  namespace: gitlab
  labels:
    app.kubernetes.io/name: blog-app
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: blog-app
      app.kubernetes.io/instance: app
  template:
    metadata:
      annotations:
        checksum_db-env-secret : 1f18af3930390672736998cc4ec83306d2003d4e398431344621bb5a6e89ed74
      labels:
        app.kubernetes.io/name: blog-app
        app.kubernetes.io/instance: app
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: app
          image: blog:1.0.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256M
              cpu: 100m
            limits:
              memory: 256M
              cpu: 200m
          command:
            - java
          args:
            - -jar
            - blog-0.0.1.jar
          envFrom:
            - secretRef:
                name: db-env-secret
---
# Source: blog/templates/app.yml
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-liquibase-deployment
  namespace: gitlab
  labels:
    app.kubernetes.io/name: blog-liquibase
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blog-liquibase
      app.kubernetes.io/instance: app
  template:
    metadata:
      annotations:
        checksum_db-env-secret : 1f18af3930390672736998cc4ec83306d2003d4e398431344621bb5a6e89ed74
        checksum_liquidbase-configfile : f33f57ac7de8ad72f492a1523f959b99190fa0c50ddc07c53f92362f578d56cb
      labels:
        app.kubernetes.io/name: blog-liquibase
        app.kubernetes.io/instance: app
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: liquibase
          image: liquibase:4.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256M
              cpu: 100m
            limits:
              memory: 256M
              cpu: 200m
          command:
            - liquibase
          args:
            - update --url="jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}"
            - --username=$POSTGRES_USER
            - --password=$POSTGRES_PASSWORD
            - --driver=$POSTGRES_DRIVER
            - --changelog-file=changelog/db.changelog-master.yml
          envFrom:
            - secretRef:
                name: db-env-secret      
          volumeMounts:
            - mountPath: /liquibase/changelog/liquibase.properties
              name: liquidbase-configfile
              subPath: liquibase.properties
      volumes:
        - name: liquidbase-configfile
          configMap:
            name: liquidbase-configfile
---
# Source: blog/templates/app.yml
---
