version: '3.7'
services:
  postgres_blog:
    image: postgres_blog #обязательно поле, без него testcontainer создает новые образы
    build:
      context: .
      dockerfile: dockerfile_db
    ports:
      - "5001:5432"
    networks:
      - myNetwork
  pgadmin_blog:
    image: pgadmin_blog
    build:
      context: .
      dockerfile: dockerfile_pgadmin
    ports:
      - "8484:80"
    networks:
      - myNetwork
    depends_on:
      - postgres_blog
  liquidbase_blog:
    image: liquibase/liquibase:4.10
    build:
      context: .
      dockerfile: dockerfile_liquidbase
    depends_on:
      - pgadmin_blog
    volumes:
      - import/db/:/liquibase/changelog/
    command:  --defaults-file=/liquibase/changelog/liquibase.properties update
    networks:
      - myNetwork
  blog:
    image: blog
    build:
      context: .
      dockerfile: dockerfile_java
    depends_on:
      - liquidbase_blog
    volumes:
    - ../../build/libs:/app
    ports:
      - "9898:8080"
    command: java -jar blog-0.0.1-SNAPSHOT.jar
    networks:
      - myNetwork
volumes:
  db-data:
    external: true
networks:
  myNetwork:
    external: true

