spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  datasource:
    hikari:
      driver-class-name: 'org.h2.Driver'
Mytest:
  blog-feignClient:
    url: http://localhost:8080
    user:
      url: /user
      name-client: userFiegnClient
