Mytest:
  blog-feignClient:
    url: http://localhost:9898
    user:
      url: /user
      name-client: userFiegnClient
  env:
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_PORT: ${POSTGRES_PORT}
    POSTGRES_DRIVER: ${POSTGRES_DRIVER}
    POSTGRES_URL: ${POSTGRES_URL}