projectName:  "blog"
namespace: &namespace gitlab
apps:
  liquibase:
    name: "liquibase"
    namespace: *namespace
    replicasCount: 1
    secretMaps:
      - db-env-secret
    container:
      image: liquibase
      version: 4.10
      port: 8080
      command:
        - liquibase
      args:
        - update --url="jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}"
        - --username=$POSTGRES_USER
        - --password=$POSTGRES_PASSWORD
        - --driver=$POSTGRES_DRIVER
        - --changelog-file=changelog/db.changelog-master.yml
  blog:
    name: "app"
    namespace: *namespace
    replicasCount: 2
    container:
      image: blog
      version: 1.0.0
      port: 8080
    service:
      port: 8080
      targetPort: 8080
      nodePort: 30022
      type: NodePort
    secretMaps:
      - db-env-secret
secret:
  dbEnvSecret:
    name: "db-env-secret"
    data:
      POSTGRES_DB: blog
      POSTGRES_USER: main_user
      POSTGRES_PASSWORD: main_pass
      POSTGRES_PORT: 5432
      POSTGRES_DRIVER: org.postgresql.Driver
      POSTGRES_URL: 192.168.1.81